### ISSUE TITLE
ProjectKnife: Document Support

### ISSUE THREAD

**Issue by ptruble** [projectknife/pkg-projectknife#39] opened 2017-07-20 20:16 UTC
Does ProjectKnife have a repository for documents linked to projects? I have looked throught the demo and see nowhere where that feature has been brought forward.

**Comment by micker** [comment] 2017-07-21 08:30
its planned but they rebuild feature step by step

**Comment by eaxs** [comment] 2017-07-22 12:37
@micker is right. I'll close this issue because it is a duplicate of #22

**Closed by eaxs** 2017-07-22 12:37 UTC
Labels: enhancement
